spring:
  application:
    name: VotingApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    # to disable transactions at the controller level by default
    open-in-view: false

client:
  host: localhost
  port: 8080

tcpserver:
  port: 8080


